--liquibase formatted sql

--changeset sergej:1
CREATE TABLE INVOICE
(
    ID                      BIGSERIAL                     PRIMARY KEY,
    PAYMENT_AMOUNT          FLOAT,
    ORDERS_ID                BIGINT,
    PAYMENT_RESULT_ID       BIGINT,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS (ID)
);

--changeset sergej:2
ALTER TABLE ORDERS ADD CONSTRAINT FK_INVOICE_ID FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID);
